"""Add is_default to currency table

Revision ID: 26a9b61b4500
Revises: 5b4119619c1a
Create Date: 2025-05-09 10:51:23.080079

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '26a9b61b4500'
down_revision = '5b4119619c1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency', sa.Column('is_default', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('currency', 'is_default')
    # ### end Alembic commands ###
